version: 2.1
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/node:chakracore-10.13
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and run docker container for server tests ; Update codecov results
          command: |
            docker build -f Dockerfile.test -t arkhn/dashboard:latest .
            docker run --name dashboard_test arkhn/dashboard:latest
            docker cp dashboard_test:/usr/src/app/coverage .
            bash <(curl -s https://codecov.io/bash)
